### ISSUE TITLE
Loggregator no longer uses etcd

### ISSUE THREAD

**Issue by ljarzynski** [pivotal-cf/docs-on-demand-service-broker#11]
@avade I've been combing through the Pivotal docs for mentions of etcd and noticed we mention etcd in the ODB SDK "Operating" topic: https://github.com/pivotal-cf/docs-on-demand-service-broker/blob/v0.15.x/operating.html.md.erb#L285. 

Now that Loggregator no longer uses etcd, should we remove those lines?

**Comment by avade** [comment]
@ljarzynski are there docs anywhere that show how to configure Loggregator for a specific PCF version? 

I would be happy to simply point to the loggregator docs instead of maintaining a copy.

cc @ahevenor

**Comment by ahevenor** [comment]
This is a good idea to add to official PCF docs.  I have the relevant info in this [google doc](https://docs.google.com/document/d/138fJFef1tX5ho0Rvc_tmX9RgFqDXVO0db0bqVGOPRd4/edit).

**Comment by avade** [comment]
Any updates on this @ljarzynski / @ahevenor ?

**Comment by ljarzynski** [comment]
@avade Apologies for the late response. 

Looking at the Broker Metrics section that mentions etcd (https://docs.pivotal.io/svc-sdk/odb/0-17/operating.html#broker-metrics), I'm unsure how to update the manifest snippet or where to point to if we remove it. The Google doc provided by @ahevenor seems to be more of a table showing compatibility. The only other related section I can think of is here: http://docs.pivotal.io/tiledev/nozzle.html. But I'm not sure if that's the right place to link or place Adam's info. I would be happy to make/publish the updates, but could use a little more guidance.

**Comment by avade** [comment]
Updated to point to examples in service-metrics
