### ISSUE TITLE
Link to Kafka app doesn't work

### ISSUE THREAD

**Issue by MeBNoah** [pivotal-cf/docs-on-demand-service-broker#8]
On one of the getting started pages for the ODB(https://docs.pivotal.io/svc-sdk/odb/0-15/getting-started.html) the link to the kafka example app(https://github.com/pivotal-cf-experimental/kafka-example-app) is not working.

**Comment by pspinrad** [comment]
Looks like it's a permissions problem -- link works if I'm logged into Github.

@avade can kafka-example-app repo be public, like kafka-example-service-adapter and kafka-example-service-release are?  Thanks!

**Comment by avade** [comment]
Now public - apologies!
