### ISSUE TITLE
cloud config ip ranges conflict w/ OOTB cf-release deployment

### ISSUE THREAD

**Issue by pegadave** [pivotal-cf/docs-on-demand-service-broker#9]
Under step 5, the cloud-config.yml (as pictured) specifies an IP range (10.244.0.0/24) and gateway (10.244.0.1) the conflicts with the OOTB cf-release.  Not a big deal to figure out, but it would probably make for a more pleasant working-through-the-example experience.

**Comment by pspinrad** [comment]
@avade Looking at this code example in ODB docs: http://docs.pivotal.io/svc-sdk/odb/0-15/getting-started.html#create_bosh

What network addresses for kafka would be consistent with cf-release?  Thanks!

**Comment by avade** [comment]
Thanks, @pegadave we will look into changing this.

**Comment by pegadave** [comment]
I used 10.244.1.* and that sufficed.

**Comment by pspinrad** [comment]
Change from @simonjjones publishes here: http://docs.pivotal.io/svc-sdk/odb/0-16/getting-started.html#create_bosh  Belated thanks Simon for fixing this!
